### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by Dantae-Jekins** [farinap5/Venera#1]
hmmmmmmmmmmmmmmmmmmmmm
Nun liebe Kinder gebt fein Acht
ich bin die Stimme aus dem Kissen
ich hab euch etwas mitgebracht
hab es aus meiner Brust gerissen
mit diesem Herz hab ich die Macht
die Augenlider zu erpressen
ich singe bis der Tag erwacht
ein heller Schein am Firmament
Mein Herz brennt

Sie kommen zu euch in der Nacht
Dämonen Geister schwarze Feen
sissoe kriechen aus de me cheira Kellerschacht

und werden unter euer Bettzeug sehen

Nun liebe Kinder gebt fein Acht
isso me  cheira a
ich bin die Stimme aus dem Kissen
ich hab euch etwas mitgebracht
ein heller Schein am Firmament
Mein Herz Brennt
 
Mein Herz Brennt
 

Sie kommen zu euch in der Nacht
metasploit  da shoppe, gostei
und stehlen eure kleinen heissen Tränen
sie warten bis der Mond erwacht
und drücken sie in meine kalten Venen
 

tome uma estrelinha aqui
Nun liebe Kinder gebt fein Acht
🤓🤓🤓🤓🤓🤓🤓🤓
ich bin die Stimme aus dem Kissen
ich singe bis der Tag erwacht
ein heller Schein am Firmament
Mein Herz brennt

### README.md
Erro de anglo saxão contemporâneo 
[ ``` `search match <key>` list witch maches patter. ```](https://github.com/farinap5/Venera/blob/488e9687fbcf78ac14f79fc192f7fd3426e376c9/README.md?plain=1#L48)

**Comment by farinap5** [comment]
Danke freund. Gutes lied.
