### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by farinap5** [farinap5/Venera#16]
Create Dockerfile and instructions to use it.

**Comment by Bhanuteja01** [comment]
assign me this

**Comment by farinap5** [comment]
> assign me this

Hey! Done!!

**Comment by farinap5** [comment]
Dockerfile done and tested. commited [03b9a84](https://github.com/farinap5/Venera/commit/03b9a8464bce6f7340b368134f47dbcdda3d8f0b)
