### ISSUE TITLE
[miniguide] fixup for MacOS

### ISSUE THREAD

**Issue by nekkitl** [farinap5/Venera#23]
```
It seems like your first time running it!
[+]- Setting up ~/.venera
Fatal error: mkdir home/nickognev/.venera: no such file or directory
```
To fix this - go to `src/db/dbveneradir.go` and `src/db/dbinit.go` and change path from `/home/+uname` to `/Users/+uname`.

**Comment by farinap5** [comment]
Hey! Thank you a lot!!

I will be taking in account for the next commits.
